baseurl = "https://www.dl07.vip"
defaultContentLanguage = "zh"
languageCode = "zh"
title = "章鱼腿很长"
theme = "dream"

enableRobotsTXT = true

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

author = "章鱼"
# description = ""
 avatar = "img/avatar.png"
headerTitle = "章鱼腿很长"
 motto = "不设限，做个行动的巨人！"

# footerBottomText = "123"

 rss = true

# utterancesRepo = ""

 #valine = true
 #LEANCLOUD_APP_ID = ""
 #LEANCLOUD_APP_KEY = ""

 waline = true
 walineServer = "https://commnet.dl07.vip/.netlify/functions/comment"

 email = "dl07vip@163.com"

siteStartYear = 2025

 favicon = "img/favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
 stickyNav = true
# reorderNavItems = ["search", "rss", "posts", "categories", "tags", "serise"]
 collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
 showTableOfContents = true
# showSummaryCoverInPost = true
# imageZoomableInPost = true
 showPrevNextPost = true
 reorderShares = ["x", "facebook", "whatsapp"]

# [params.navItems]
#[params.navItems]
#series = { href = "/series", icon = "planet", title = "Series" }


# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"

[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
  excludeFiles = ['posts/_Templates']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

 [params.busuanzi]
        enable = true
